rules: support series files for file fetch dependencies
Expecting a newline separated list of patch filenames.
Currently the rule depends only on the .series file, and not the patches
that it refers to.
This might change in the future with automatically created .d files.

diff --git a/tools/git-clone b/tools/git-clone
--- a/tools/git-clone
+++ b/tools/git-clone
@@ -56,9 +56,36 @@ rm -rf "$DEST_DIR"
 git clone "$CLONE_DIR" "$DEST_DIR"
 git -C "$DEST_DIR" checkout "$REFNAME" --
 
-for patch in $PATCHES; do
-	echo "Applying patch $patch" >&2
-	git -C "$DEST_DIR" am "$(pwd)/$patch" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$patch"
+for fn in $PATCHES; do
+	case "$fn" in
+		*.patch)
+			echo "Applying patch: $fn" >&2
+			git -C "$DEST_DIR" am "$(pwd)/$fn" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$fn"
+			;;
+		*.series)
+			echo "Applying patch series: $fn" >&2
+			while IFS= read -r patch; do
+				case "$patch" in
+					\#*)
+						echo "Skipping patch in series: $patch" >&2
+						;;
+					*.patch)
+						echo "Applying patch in series: $patch" >&2
+						git -C "$DEST_DIR" am "$(pwd)/$patch" || patch -d "$DEST_DIR" -p1 -i "$(pwd)/$patch"
+						;;
+					'') ;; # Skip blank lines
+					*)
+						echo "ERROR: Not a patch: $patch"
+						exit 1
+						;;
+				esac
+			done < "$fn"
+			;;
+		*)
+			echo "ERROR: Not a patch or patch series: $fn"
+			exit 1
+			;;
+	esac
 done
 
 echo "git $URL $REFNAME $PATCHES" > "$DEST_DIR.src"
